### ISSUE TITLE
How to change the colors?

### ISSUE THREAD

**Issue by andreasba** [Globegitter/chartist-plugin-tooltip#48]
Hi there,

thanks for this great plugin!

However, I cannot get one thing to work: I want to change the colors. My CSS looks like this

```CSS
.chartist-tooltip {
    background: #337fcc;
    color: white;
    border-color: #337fcc;
}
```
And it works - except for the "arrow" which stays yellow :-)

![picture](https://cloud.githubusercontent.com/assets/15323226/12218703/da392c86-b727-11e5-8981-6efad5042f13.jpg)

What did I miss?

Thanks
Andreas
